// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaqmwiugcnqijkzialyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhcW13aXVnY25xaWpremlhbHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODU0OTMsImV4cCI6MjA2NTQ2MTQ5M30.eI96Qw6Wdvt6hdu0LasqkeRIj4ghwUETVPpKlSSchtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);